/*--------------------------------------------------------------------------
 ** This file is autogenerated from config.h.in 
 ** during the cmake configuration of your project. If you need to make changes
 ** edit the original file NOT THIS FILE.
 ** --------------------------------------------------------------------------*/
#ifndef _CONFIGURATION_HEADER_GUARD_H_
#define _CONFIGURATION_HEADER_GUARD_H_

#define SIZEOF_INT 
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
/* #undef HAVE_FLOOR */
/* #undef HAVE_CEIL */
/* #undef HAVE_MEMSET */
/* #undef HAVE_POW */
/* #undef HAVE_SQRT */
/* #undef HAVE_SIN */
/* #undef HAVE_COS */
/* #undef HAVE_ATAN2 */
/* #undef HAVE_LOG10 */
/* #undef HAVE_ROUND */
/* #undef HAVE_GETOPT */
#endif
